;; Sarah's emacs configurator.

;; Configuration for specific programming related major modes.

;; Author: Sarah Mount <(concat "snim2" at-symbol "snim2.org")>

;; Copyright (C) Sarah Mount, 2010.

;; This file is NOT part of GNU Emacs.

;; This program is free software; you can redistribute it and/or
;; modify it under the terms of the GNU General Public License
;; as published by the Free Software Foundation; either version 2
;; of the License, or (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.


(message "Loading programming mode configuration.")

;;; Local elisp packages.
(add-to-list 'load-path "~/.emacs.d/elisp/scala")

;; howdoi: look up answers from the command line.
(when (file-exists-p "~/.emacs.d/elisp/howdoi.el")
  (load-file "~/.emacs.d/elisp/howdoi.el"))

;;; MELPA packages.
(use-package git-gutter-fringe
  :ensure t
  :config
  (global-git-gutter-mode 1))

(use-package elpy
  :ensure t
  :init
  (elpy-enable))

(use-package rainbow-delimiters
  :ensure t)

(use-package go-mode
  :ensure t)

;; pomodoro timer (local copy).
(when (require 'pomodoro nil t)
  (pomodoro-add-to-mode-line))

;; Assembler mode (local copy).
(autoload 'gas-mode "gas-mode" "Edit assembler" t)

;; OTT semantics mode (local copy).
(autoload 'ott-mode "ott-mode" "Edit semantics" t)

;; PHP mode (local copy).
(autoload 'php-mode "php-mode" "Edit PHP" t)

;; TableGen mode (local copy).
(autoload 'tablegen-mode "tablegen-mode" "Quickly create tables" t)

;; CPF files (local copy).
(autoload 'cpf-mode "cpf-mode")
(setq auto-mode-alist (cons '("\\.cpf\\'" . cpf-mode) auto-mode-alist))

;; Indentation.
(setq c-basic-offset 4)
(setq-default indent-tabs-mode nil)

;;; Changelogs.
(setq change-log-default-name "ChangeLog")


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;; Configuration for specific programming modes.                         ;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;;; SML: display "fn" as λ.
(defun pretty-fns ()
  (font-lock-add-keywords
   nil `(("(\\(fn\\>\\)"
          (0 (progn (compose-region (match-beginning 1) (match-end 1) ?λ)
                    nil))))))
(add-hook 'sml-mode-hook 'pretty-fns)

;;; Actionscript 3.
(setq auto-mode-alist
      (cons '("\\.as$" . actionscript) auto-mode-alist))

;;; Maxima.
(setq auto-mode-alist (cons '("\\.max" . maxima-mode) auto-mode-alist))
(autoload 'maxima "maxima" "Running Maxima interactively" t)
(autoload 'maxima-mode "maxima" "Maxima editing mode" t)

;;; Java: insert a public class definition into any new .java file.
(defun snim2-java-insert-public-class ()
  (let ((filename (buffer-file-name (current-buffer))))
    (when (and (= 1 (point-max)) filename)
      (let ((classname (file-name-sans-extension
                        (file-name-nondirectory filename))))
        (skeleton-insert
         '(nil "public class " classname " {\n"
               > _
               "\n}"))))))

(defun snim2-java-setup ()
  (c-set-style "k&r")
  (setq c-basic-offset 4)
  (c-set-offset 'case-label '+))

(add-hook 'java-mode-hook 'snim2-java-setup)

;;; Python.
(setq gud-pdb-command-name "python3 -m pdb")

(defun snim2-python-setup ()
  (define-key python-mode-map "\C-m" 'newline-and-indent)
  (eldoc-mode 1)
  (setq c-basic-offset 4)
  (setq python-indent-offset 4))

(add-hook 'python-mode-hook 'snim2-python-setup)

(defun python-2to3 ()
  "Convert current buffer from python 2 to python 3.
   This command calls python3's script 2to3.
   A backup will be generated by 2to3 and named FILENAME.bak."
  (interactive)
  (let* ((fName (buffer-file-name))
         (fSuffix (file-name-extension fName)))
    (when (buffer-modified-p)
      (when (y-or-n-p "Buffer modified. Do you want to save first?")
        (save-buffer)))
    (if (or (string-equal fSuffix "py") (string-equal fSuffix "py3"))
        (progn
          (shell-command (format "2to3 -w %s" fName))
          (revert-buffer "IGNORE-AUTO" "NOCONFIRM" "PRESERVE-MODES"))
      (error "file \"%s\" doesn't end in \".py\" or \".py3\"." fName))))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;; Configuration for all programming related major modes.                ;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; Tab-completion for programming modes.
(defun indent-or-expand (arg)
  "Either indent or expand, depending on context."
  (interactive "*P")
  (if (and
       (or (bobp) (= ?w (char-syntax (char-before))))
       (or (eobp) (not (= ?w (char-syntax (char-after))))))
      (hippie-expand arg)
    (indent-according-to-mode)))
(defun my-tab-fix ()
  (local-set-key [tab] 'indent-or-expand))

;; Abbreviations.
(setq save-abbrevs t)
(setq abbrev-verbose t)
(when (file-exists-p "~/.emacs.d/abbrev_defs")
  (load "~/.emacs.d/abbrev_defs"))


(defun hilite-todos ()
  (highlight-lines-matching-regexp
   "\\<\\(FIXME\\|WRITEME\\|WRITEME!\\|TODO\\|BUG\\):?"
   'hi-green-b))

(defun my-prog-config ()
  "Set minor modes and other config for all programming related modes."
  (abbrev-mode 1)
  (display-line-numbers-mode 1)
  (pretty-greek)
  (hilite-todos)
  (when (fboundp 'git-gutter-mode)
    (git-gutter-mode 1)
    (set-face-foreground 'git-gutter-fr:deleted "red"))
  (my-tab-fix)
  (show-paren-mode 1)
  (flyspell-prog-mode)
  (when (fboundp 'rainbow-delimiters-mode)
    (rainbow-delimiters-mode 1))
  (setq time-stamp-active t
        time-stamp-line-limit 10
        time-stamp-format "%02d-%02m-%04y %02H:%02M:%02S (%u)")
  (add-hook 'before-save-hook 'time-stamp nil t)
  (font-lock-add-keywords nil
                          '(("^[^\n]\\{80\\}\\(.*\\)$" 1 font-lock-warning-face t))))


(add-hook 'actionscript-mode-hook 'my-prog-config)
(add-hook 'autoconf-mode-hook 'my-prog-config)
(add-hook 'c++-mode-hook 'my-prog-config)
(add-hook 'c-mode-hook 'my-prog-config)
(add-hook 'cperl-mode-hook 'my-prog-config)
(add-hook 'emacs-lisp-mode-hook 'my-prog-config)
(add-hook 'xml-mode-hook 'my-prog-config)
(add-hook 'elpy-mode-hook 'my-prog-config)
(add-hook 'sh-mode-hook 'my-prog-config)
(add-hook 'go-mode-hook 'my-prog-config)
(add-hook 'c-mode-common-hook 'my-prog-config)
(add-hook 'java-mode-hook 'my-prog-config)
(add-hook 'latex-mode-hook 'my-prog-config)
(add-hook 'tex-mode-hook 'my-prog-config)
(add-hook 'sml-mode-hook 'my-prog-config)
(add-hook 'prolog-mode-hook 'my-prog-config)
