#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

shellcheck --version

git ls-files -z -c '*.bash' \
                   '*.sh' \
                   '_bash*' \
                   '_zsh*' \
                   '_zshrc/*' \
                   '_zshrc.d/*' \
                   'script/*' \
                   'bin/*' | xargs -0 shellcheck --shell=bash --color=always --external-sources --check-sourced

echo "Shellcheck: OK."
