name: Linter and secret scanner

on: push

jobs:
  lint-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        uses: actions/checkout@v3
      - name: Run lints
        run: ./hooks/pre-commit
      - name: Scan for secrets
        uses: secret-scanner/action@0.0.2
